#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Problem 2 - Even Fibonacci numbers
# https://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

limit = 4000000
fibs  = [1,1]
last  = 0
total = 0

while last < limit:
    last = fibs[-1] + fibs[-2]

    if last < limit:
        fibs.append(last)

        if not last & 0x1:
            total += last

print total

# Congratulations, the answer you gave to problem 2 is correct.
# You are the 340750th person to have solved this problem.